//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.18408")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.0")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_lm25o2vh {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_lm25o2vh() {
        }
        
        static object Create_ASP_inventory_inventorycheck_qm_aspx() {
            return new ASP.inventory_inventorycheck_qm_aspx();
        }
        
        static object Create_ASP_inventory_inventoryreview_am_aspx() {
            return new ASP.inventory_inventoryreview_am_aspx();
        }
        
        static object Create_ASP_inventory_stockreout_qm_aspx() {
            return new ASP.inventory_stockreout_qm_aspx();
        }
        
        static object Create_ASP_inventory_stockout_qd_aspx() {
            return new ASP.inventory_stockout_qd_aspx();
        }
        
        static object Create_ASP_inventory_materialtype_qd_aspx() {
            return new ASP.inventory_materialtype_qd_aspx();
        }
    }
}
