#pragma checksum "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1B10D243A6DED4AB0DCF26E39C31E7495108E26D"
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------



public partial class _Default : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 62 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    protected global::AjaxControlToolkit.ToolkitScriptManager ScriptManager1;
    
    #line default
    #line hidden
    
    
    #line 80 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_newpw;
    
    #line default
    #line hidden
    
    
    #line 91 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_newpwcheck;
    
    #line default
    #line hidden
    
    
    #line 96 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    protected global::System.Web.UI.WebControls.Label Label1;
    
    #line default
    #line hidden
    
    
    #line 99 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    protected global::System.Web.UI.WebControls.Button Button1;
    
    #line default
    #line hidden
    
    
    #line 102 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    protected global::System.Web.UI.WebControls.Button Button2;
    
    #line default
    #line hidden
    
    
    #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    protected global::System.Web.UI.UpdatePanel UpdatePanel2;
    
    #line default
    #line hidden
    
    
    #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 4 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    using AjaxControlToolkit;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
    using System.Web.UI.DataVisualization.Charting;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class system_loginchpwd_aspx : global::_Default, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.system_loginchpwd_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static System.Reflection.MethodInfo @__PageInspector_BeginRenderTracingMethod = global::ASP.system_loginchpwd_aspx.@__PageInspector_LoadHelper("BeginRenderTracing");
        
        private static System.Reflection.MethodInfo @__PageInspector_EndRenderTracingMethod = global::ASP.system_loginchpwd_aspx.@__PageInspector_LoadHelper("EndRenderTracing");
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public system_loginchpwd_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/System/Loginchpwd.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.system_loginchpwd_aspx.@__initialized == false)) {
                global::ASP.system_loginchpwd_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/System/Loginchpwd.aspx";
                dependencies[1] = "~/System/Loginchpwd.aspx.cs";
                global::ASP.system_loginchpwd_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.system_loginchpwd_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
                    ".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        98,
                        127,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Runtime, Version=1.3.0.0, Culture=neutral, Publi" +
                    "cKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.system_loginchpwd_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.system_loginchpwd_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_BeginRenderTracing(object[] parameters) {
            if ((global::ASP.system_loginchpwd_aspx.@__PageInspector_BeginRenderTracingMethod != null)) {
                global::ASP.system_loginchpwd_aspx.@__PageInspector_BeginRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_EndRenderTracing(object[] parameters) {
            if ((global::ASP.system_loginchpwd_aspx.@__PageInspector_EndRenderTracingMethod != null)) {
                global::ASP.system_loginchpwd_aspx.@__PageInspector_EndRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        317,
                        47,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("維運管理系統-變更密碼");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        398,
                        11,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl1 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        391,
                        26,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control7() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Href = "../css/impromptu.css";
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "Stylesheet");
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        423,
                        69,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Href = "../css/login.css";
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        498,
                        65,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Href = "../css/bootstrap/bootstrap-responsive.css";
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        569,
                        90,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 11 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 11 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Href = "../css/bootstrap/bootstrap.css";
            
            #line default
            #line hidden
            
            #line 11 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 11 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        665,
                        79,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl1 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl2;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl2 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl3;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl3 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl4;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl4 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl5;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl5 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control4));
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        364,
                        21,
                        false});
            return @__ctrl;
        }
        
        private void @__Render__control4(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[0].RenderControl(@__w);
            parameterContainer.Controls[1].RenderControl(@__w);
            parameterContainer.Controls[2].RenderControl(@__w);
            parameterContainer.Controls[3].RenderControl(@__w);
            parameterContainer.Controls[4].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/D:/Source/DotNet/ParkingRepairSystemKAO/System/Loginchpwd.aspx",
                        744,
                        390,
                        true});
            this.WriteUTF8ResourceString(@__w, 0, 390, true);
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/D:/Source/DotNet/ParkingRepairSystemKAO/System/Loginchpwd.aspx",
                        1134,
                        23,
                        false});
            
            #line 19 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
                                         @__w.Write(txt_newpw.ClientID);

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/D:/Source/DotNet/ParkingRepairSystemKAO/System/Loginchpwd.aspx",
                        1157,
                        65,
                        true});
            @__w.Write("\').value;\r\n            var newpwcheck = document.getElementById(\'");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/D:/Source/DotNet/ParkingRepairSystemKAO/System/Loginchpwd.aspx",
                        1222,
                        28,
                        false});
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
                                              @__w.Write(txt_newpwcheck.ClientID);

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/D:/Source/DotNet/ParkingRepairSystemKAO/System/Loginchpwd.aspx",
                        1250,
                        605,
                        true});
            this.WriteUTF8ResourceString(@__w, 390, 717, false);
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/D:/Source/DotNet/ParkingRepairSystemKAO/System/Loginchpwd.aspx",
                        1855,
                        23,
                        false});
            
            #line 44 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
                                 @__w.Write(txt_newpw.ClientID);

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/D:/Source/DotNet/ParkingRepairSystemKAO/System/Loginchpwd.aspx",
                        1878,
                        246,
                        true});
            @__w.Write("\').value.length < 6) {\r\n                alert(\"密碼長度需大於6個字元\");\r\n                re" +
                    "turn false;\r\n            }\r\n\r\n        }\r\n    </script>\r\n\r\n\r\n    <style type=\"tex" +
                    "t/css\">\r\n        .auto-style3 {\r\n            width: 131px;\r\n        }\r\n    </sty" +
                    "le>\r\n");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/D:/Source/DotNet/ParkingRepairSystemKAO/System/Loginchpwd.aspx",
                        2124,
                        7,
                        false});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2131,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n       \r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2191,
                        19,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.ToolkitScriptManager @__BuildControlScriptManager1() {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl;
            
            #line 62 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::AjaxControlToolkit.ToolkitScriptManager();
            
            #line default
            #line hidden
            this.ScriptManager1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 62 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.ID = "ScriptManager1";
            
            #line default
            #line hidden
            
            #line 62 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.CombineScripts = false;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2210,
                        111,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        </asp:ScriptManager>\r\n        <div id=\"main\">\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2321,
                        69,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                    <div id=""login-form"">
                        <table>
                            <tr>
                                <th colspan=""2"">變更密碼<hr />
                                </th>
                            </tr>
                            <tr>
                                <td class=""auto-style3"">
                                    <p>
                                        新密碼:
                                    </p>
                                </td>
                                <td align=""right"">
                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2500,
                        594,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_newpw() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 80 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_newpw = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 80 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.ID = "txt_newpw";
            
            #line default
            #line hidden
            
            #line 80 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3094,
                        77,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                </td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td class=""auto-style3"">
                                    <p>
                                        確認新密碼:
                                    </p>
                                </td>
                                <td align=""right"">
                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3171,
                        475,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_newpwcheck() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 91 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_newpwcheck = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 91 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.ID = "txt_newpwcheck";
            
            #line default
            #line hidden
            
            #line 91 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3646,
                        82,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                </td>\r\n                                <td>&nbs" +
                    "p;</td>\r\n                            </tr>\r\n                            <tr>\r\n  " +
                    "                              <td class=\"auto-style3\">登入帳號:");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3728,
                        220,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 96 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 96 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.ID = "Label1";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3948,
                        50,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                </td>\r\n                                <td alig" +
                    "n=\"right\">\r\n                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3998,
                        129,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlButton1() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 99 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.Button1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 99 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.ID = "Button1";
            
            #line default
            #line hidden
            
            #line 99 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Text = "確認變更";
            
            #line default
            #line hidden
            
            #line 99 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.OnClientClick = "return checkquery();";
            
            #line default
            #line hidden
            
            #line 99 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Click += new System.EventHandler(this.Button1_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4127,
                        115,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control19() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                </td>\r\n                                <td alig" +
                    "n=\"right\">\r\n                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4242,
                        129,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlButton2() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 102 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.Button2 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 102 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.ID = "Button2";
            
            #line default
            #line hidden
            
            #line 102 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Text = "取消";
            
            #line default
            #line hidden
            
            #line 102 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 102 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Click += new System.EventHandler(this.Button2_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4371,
                        92,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                </td>\r\n                            </tr>\r\n     " +
                    "                   </table>\r\n                    </div>\r\n                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4463,
                        154,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control14(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl1 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl2 = this.@__BuildControltxt_newpw();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl3 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl4 = this.@__BuildControltxt_newpwcheck();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl5 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl6;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl6 = this.@__BuildControlLabel1();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl7 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl8;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl8 = this.@__BuildControlButton1();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl9 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl10;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl10 = this.@__BuildControlButton2();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl11 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.AsyncPostBackTrigger @__BuildControl__control22() {
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl;
            
            #line 109 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.AsyncPostBackTrigger();
            
            #line default
            #line hidden
            
            #line 109 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.ControlID = "Button1";
            
            #line default
            #line hidden
            
            #line 109 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.EventName = "Click";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control21(System.Web.UI.UpdatePanelTriggerCollection @__ctrl) {
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl1;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl1 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel2() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            
            #line default
            #line hidden
            this.UpdatePanel2 = @__ctrl;
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control14));
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.ID = "UpdatePanel2";
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.UpdateMode = global::System.Web.UI.UpdatePanelUpdateMode.Conditional;
            
            #line default
            #line hidden
            
            #line 65 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            this.@__BuildControl__control21(@__ctrl.Triggers);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2390,
                        2447,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control23() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        </div>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4837,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl.Method = "post";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl1 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl2;
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl2 = this.@__BuildControlScriptManager1();
            
            #line default
            #line hidden
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl3 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.UpdatePanel @__ctrl4;
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl4 = this.@__BuildControlUpdatePanel2();
            
            #line default
            #line hidden
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl5 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 60 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2145,
                        2721,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control24() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4866,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(system_loginchpwd_aspx @__ctrl) {
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl2;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl3;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl3 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl4;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl4 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl5;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl5 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl6;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__ctrl6 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\Source\DotNet\ParkingRepairSystemKAO\System\Loginchpwd.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.system_loginchpwd_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.system_loginchpwd_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 36344742;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
