#pragma checksum "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "93DF14EF011BA78C57C7EA78AF99C363612C2900"
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------



public partial class VDCheck_VDCheckError_Q : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
    
    #line default
    #line hidden
    
    
    #line 115 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::AjaxControlToolkit.ToolkitScriptManager ScriptManager1;
    
    #line default
    #line hidden
    
    
    #line 121 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.WebControls.LinkButton cmd_Search;
    
    #line default
    #line hidden
    
    
    #line 123 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.WebControls.DropDownList ddlst_SearchType;
    
    #line default
    #line hidden
    
    
    #line 125 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_Query_Reason;
    
    #line default
    #line hidden
    
    
    #line 128 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_StartDate;
    
    #line default
    #line hidden
    
    
    #line 129 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_EndDate;
    
    #line default
    #line hidden
    
    
    #line 133 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.WebControls.LinkButton lnkbtn_Report;
    
    #line default
    #line hidden
    
    
    #line 135 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.WebControls.LinkButton lnkbtn_Add;
    
    #line default
    #line hidden
    
    
    #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.WebControls.Panel SearchPanel;
    
    #line default
    #line hidden
    
    
    #line 146 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.UpdateProgress UpdateProgress1;
    
    #line default
    #line hidden
    
    
    #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.WebControls.GridView gv;
    
    #line default
    #line hidden
    
    
    #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.UpdatePanel UpdatePanel1;
    
    #line default
    #line hidden
    
    
    #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 3 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    using AjaxControlToolkit;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
    using System.Web.UI.DataVisualization.Charting;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class vdcheck_vdcheckerror_q_aspx : global::VDCheck_VDCheckError_Q, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public vdcheck_vdcheckerror_q_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/VDCheck/VDCheckError_Q.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.vdcheck_vdcheckerror_q_aspx.@__initialized == false)) {
                global::ASP.vdcheck_vdcheckerror_q_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[3];
                dependencies[0] = "~/VDCheck/VDCheckError_Q.aspx";
                dependencies[1] = "~/VDCheck/VDCheckError_Q.aspx.cs";
                dependencies[2] = "~/checkpass.inc";
                global::ASP.vdcheck_vdcheckerror_q_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.vdcheck_vdcheckerror_q_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "Stylesheet");
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Href = "../css/web.css";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "Stylesheet");
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Href = "../css/impromptu.css";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Href = "../css/bootstrap/bootstrap-responsive.css";
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 11 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 11 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Href = "../css/bootstrap/bootstrap.css";
            
            #line default
            #line hidden
            
            #line 11 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 11 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 16 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 16 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Href = "../css/impromptu.css";
            
            #line default
            #line hidden
            
            #line 16 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "Stylesheet");
            
            #line default
            #line hidden
            
            #line 16 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control7() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 17 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 17 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            
            #line 17 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Href = "../css/jquery1.10.2/jquery-ui.css";
            
            #line default
            #line hidden
            
            #line 17 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 21 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 21 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Href = "../css/jquery-ui-timepicker-addon.css";
            
            #line default
            #line hidden
            
            #line 21 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 24 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 24 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("保固設備管理-設備種類維護"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControlHead1() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            this.Head1 = @__ctrl;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "Head1";
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl1;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl2;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl3;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl3 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl4;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl4 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(1788, 260, true));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl5;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl5 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl6;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl6 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jq" +
                        "uery/1.9.1/jquery.min.js\"></script>\r\n    \r\n    <script type=\"text/javascript\" sr" +
                        "c=\"../javascript/jquery-ui-1.10.2.min.js\"></script>\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl7;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl7 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <script type=\"text/javascript\" src=\"../javascript/jquery-ui-timepicker-addo" +
                        "n.js\"></script>\r\n    <script type=\'text/javascript\' src=\'../javascript/jquery-ui" +
                        "-sliderAccess.js\'></script>\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl8;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl8 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(2048, 3007, false));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.ToolkitScriptManager @__BuildControlScriptManager1() {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl;
            
            #line 115 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::AjaxControlToolkit.ToolkitScriptManager();
            
            #line default
            #line hidden
            this.ScriptManager1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 115 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "ScriptManager1";
            
            #line default
            #line hidden
            
            #line 115 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CombineScripts = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControlcmd_Search() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            
            #line 121 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            
            #line default
            #line hidden
            this.cmd_Search = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 121 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "cmd_Search";
            
            #line default
            #line hidden
            
            #line 121 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CausesValidation = false;
            
            #line default
            #line hidden
            
            #line 121 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CssClass = "btn btn-primary";
            
            #line default
            #line hidden
            
            #line 121 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 121 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 121 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("關鍵字搜尋"));
            
            #line default
            #line hidden
            
            #line 121 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Click += new System.EventHandler(this.lnkbtn_Search_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlst_SearchType() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 123 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.ddlst_SearchType = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 123 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "ddlst_SearchType";
            
            #line default
            #line hidden
            
            #line 123 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CssClass = "dropdown";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_Query_Reason() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 125 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_Query_Reason = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 125 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "txt_Query_Reason";
            
            #line default
            #line hidden
            
            #line 125 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.AutoCompleteType = global::System.Web.UI.WebControls.AutoCompleteType.Disabled;
            
            #line default
            #line hidden
            
            #line 125 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 125 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "請輸入");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_StartDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 128 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_StartDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 128 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "txt_StartDate";
            
            #line default
            #line hidden
            
            #line 128 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "通報時間查詢");
            
            #line default
            #line hidden
            
            #line 128 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CssClass = "span3";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_EndDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 129 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_EndDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 129 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "txt_EndDate";
            
            #line default
            #line hidden
            
            #line 129 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "通報時間查詢");
            
            #line default
            #line hidden
            
            #line 129 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CssClass = "span3";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllnkbtn_Report() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            
            #line 133 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            
            #line default
            #line hidden
            this.lnkbtn_Report = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 133 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "lnkbtn_Report";
            
            #line default
            #line hidden
            
            #line 133 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 133 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CausesValidation = false;
            
            #line default
            #line hidden
            
            #line 133 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CssClass = "btn btn-primary";
            
            #line default
            #line hidden
            
            #line 133 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 133 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(60D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 133 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp;&nbsp;匯出"));
            
            #line default
            #line hidden
            
            #line 133 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Click += new System.EventHandler(this.lnkbtn_Report_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllnkbtn_Add() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            
            #line 135 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            
            #line default
            #line hidden
            this.lnkbtn_Add = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 135 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "lnkbtn_Add";
            
            #line default
            #line hidden
            
            #line 135 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 135 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CausesValidation = false;
            
            #line default
            #line hidden
            
            #line 135 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CssClass = "btn btn-primary";
            
            #line default
            #line hidden
            
            #line 135 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.OnClientClick = "return add()";
            
            #line default
            #line hidden
            
            #line 135 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 135 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(60D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 135 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp;&nbsp;新增"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlSearchPanel() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.SearchPanel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "SearchPanel";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                \r\n                    <div style=\"float: left\">\r\n              " +
                        "          "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.LinkButton @__ctrl1;
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl1 = this.@__BuildControlcmd_Search();
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl2 = this.@__BuildControlddlst_SearchType();
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl3 = this.@__BuildControltxt_Query_Reason();
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </div>\r\n                    <div id =\"SearchDate\" style=\"fl" +
                        "oat:left;display: none;\">\r\n                            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl4 = this.@__BuildControltxt_StartDate();
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<img src=\"../images/calendar.png\" />\r\n                            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl5 = this.@__BuildControltxt_EndDate();
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<img src=\"../images/calendar.png\" />\r\n\r\n                    </div>\r\n             " +
                        "       <div style=\"float: right\">\r\n                        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.LinkButton @__ctrl6;
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl6 = this.@__BuildControllnkbtn_Report();
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.LinkButton @__ctrl7;
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl7 = this.@__BuildControllnkbtn_Add();
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 118 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </div>\r\n                    \r\n                "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control11(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 146 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div class=\"progressBackgroundLayer\">\r\n                " +
                        "        </div>\r\n                        <div class=\"fixedCenter\">\r\n             " +
                        "               <img src=\"../images/ajax-loader2.gif\"></div>\r\n                   " +
                        " "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdateProgress @__BuildControlUpdateProgress1() {
            global::System.Web.UI.UpdateProgress @__ctrl;
            
            #line 146 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.UpdateProgress();
            
            #line default
            #line hidden
            this.UpdateProgress1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 146 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ProgressTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control11));
            
            #line default
            #line hidden
            
            #line 146 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "UpdateProgress1";
            
            #line default
            #line hidden
            
            #line 146 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DisplayAfter = 2;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control13() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 164 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 164 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DataField = "Num";
            
            #line default
            #line hidden
            
            #line 164 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.HeaderText = "錯誤編號";
            
            #line default
            #line hidden
            
            #line 164 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control14() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 165 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 165 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DataField = "Vdid";
            
            #line default
            #line hidden
            
            #line 165 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.HeaderText = "設備編號";
            
            #line default
            #line hidden
            
            #line 165 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control15() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 166 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 166 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DataField = "Vsrdir";
            
            #line default
            #line hidden
            
            #line 166 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.HeaderText = "偵測方向";
            
            #line default
            #line hidden
            
            #line 166 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control16() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 167 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 167 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DataField = "Week";
            
            #line default
            #line hidden
            
            #line 167 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.HeaderText = "星期";
            
            #line default
            #line hidden
            
            #line 167 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control17() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 168 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 168 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DataField = "Hours";
            
            #line default
            #line hidden
            
            #line 168 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.HeaderText = "時段";
            
            #line default
            #line hidden
            
            #line 168 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control18() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 169 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 169 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DataField = "RecordTime";
            
            #line default
            #line hidden
            
            #line 169 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.HeaderText = "資料收集時間";
            
            #line default
            #line hidden
            
            #line 169 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 169 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DataFormatString = "{0:yyyy/MM/dd HH:mm:ss}";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control19() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 170 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 170 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DataField = "Counts";
            
            #line default
            #line hidden
            
            #line 170 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.HeaderText = "連續異常次數";
            
            #line default
            #line hidden
            
            #line 170 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control20() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 171 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 171 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DataField = "UpdateTime";
            
            #line default
            #line hidden
            
            #line 171 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.HeaderText = "紀錄時間";
            
            #line default
            #line hidden
            
            #line 171 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 171 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DataFormatString = "{0:yyyy/MM/dd HH:mm:ss}";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control12(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.BoundField @__ctrl1;
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl1 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl2 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl3 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl4;
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl4 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl5;
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl5 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl6;
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl6 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl7;
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl7 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl8;
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl8 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl8);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control21(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Black;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control22(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Black;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgv() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            
            #line default
            #line hidden
            this.gv = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "gv";
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.AllowPaging = true;
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CssClass = "table table-hover ";
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.None;
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.AutoGenerateColumns = false;
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CellPadding = 4;
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.CellSpacing = 1;
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.PageSize = 12;
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            this.@__BuildControl__control12(@__ctrl.Columns);
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            this.@__BuildControl__control21(@__ctrl.FooterStyle);
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            this.@__BuildControl__control22(@__ctrl.HeaderStyle);
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.PageIndexChanging += new System.Web.UI.WebControls.GridViewPageEventHandler(this.gv_PageIndexChanging);
            
            #line default
            #line hidden
            
            #line 154 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.RowDataBound += new System.Web.UI.WebControls.GridViewRowEventHandler(this.gv_RowDataBound);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control10(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            
            #line default
            #line hidden
            global::System.Web.UI.UpdateProgress @__ctrl1;
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl1 = this.@__BuildControlUpdateProgress1();
            
            #line default
            #line hidden
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl2;
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl2 = this.@__BuildControlgv();
            
            #line default
            #line hidden
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.AsyncPostBackTrigger @__BuildControl__control24() {
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl;
            
            #line 178 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.AsyncPostBackTrigger();
            
            #line default
            #line hidden
            
            #line 178 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ControlID = "lnkbtn_Add";
            
            #line default
            #line hidden
            
            #line 178 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.EventName = "Click";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.AsyncPostBackTrigger @__BuildControl__control25() {
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl;
            
            #line 179 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.AsyncPostBackTrigger();
            
            #line default
            #line hidden
            
            #line 179 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ControlID = "cmd_Search";
            
            #line default
            #line hidden
            
            #line 179 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.EventName = "Click";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.AsyncPostBackTrigger @__BuildControl__control26() {
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl;
            
            #line 180 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.AsyncPostBackTrigger();
            
            #line default
            #line hidden
            
            #line 180 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ControlID = "lnkbtn_Report";
            
            #line default
            #line hidden
            
            #line 180 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.EventName = "Click";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control23(System.Web.UI.UpdatePanelTriggerCollection @__ctrl) {
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl1;
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl1 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl2;
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl2 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl3;
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl3 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel1() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            
            #line default
            #line hidden
            this.UpdatePanel1 = @__ctrl;
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control10));
            
            #line default
            #line hidden
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "UpdatePanel1";
            
            #line default
            #line hidden
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.UpdateMode = global::System.Web.UI.UpdatePanelUpdateMode.Conditional;
            
            #line default
            #line hidden
            
            #line 144 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            this.@__BuildControl__control23(@__ctrl.Triggers);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl.DefaultButton = "cmd_Search";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <div>\r\n    <center>\r\n    <!--上半部控制項[搜尋, 新增]-->\r\n        <div>\r\n            " +
                        ""));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl1;
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl1 = this.@__BuildControlScriptManager1();
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            <br />\r\n            <div>\r\n                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl2;
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl2 = this.@__BuildControlSearchPanel();
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </div>\r\n        </div>\r\n        \r\n        <!--資料列表-->\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.UpdatePanel @__ctrl3;
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl3 = this.@__BuildControlUpdatePanel1();
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </center>\r\n    </div>\r\n    "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(vdcheck_vdcheckerror_q_aspx @__ctrl) {
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl1 = this.@__BuildControlHead1();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\checkpass.inc"
  
 if(Session["LOGIN"]=="OK")
    {
        //登入成功，取得session
            
    }
    else
    {
        //沒有登入或是沒取得session
		Response.Write("<script>");
		Response.Write("window.alert('操作逾時，請重新登入');");
		Response.Write("window.open('../Index.aspx','_top')");
		Response.Write("</script>"); 
       // Response.Redirect("../Login.aspx");
    }

            
            #line default
            #line hidden
            @__w.Write("\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.o" +
                    "rg/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n\r\n<html xmlns=\"http://www.w3.org/199" +
                    "9/xhtml\">\r\n");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n<body>\r\n    ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n</body>\r\n</html>\r\n\r\n");
        }
        
        
        #line 912304 "D:\Source\DotNet\ParkingRepairSystemKAO\VDCheck\VDCheckError_Q.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.vdcheck_vdcheckerror_q_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.vdcheck_vdcheckerror_q_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -832255290;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
