//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.18408")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.0")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_nswlffpv {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_nswlffpv() {
        }
        
        static object Create_ASP_mis_devicekindphoto_aspx() {
            return new ASP.mis_devicekindphoto_aspx();
        }
        
        static object Create_ASP_mis_kindsofequipmentmanage_aspx() {
            return new ASP.mis_kindsofequipmentmanage_aspx();
        }
        
        static object Create_ASP_mis_project_am_aspx() {
            return new ASP.mis_project_am_aspx();
        }
        
        static object Create_ASP_mis_matrialofdevcemanage_aspx() {
            return new ASP.mis_matrialofdevcemanage_aspx();
        }
        
        static object Create_ASP_mis_regionlist_aspx() {
            return new ASP.mis_regionlist_aspx();
        }
        
        static object Create_ASP_mis_equipmentdatalist_aspx() {
            return new ASP.mis_equipmentdatalist_aspx();
        }
        
        static object Create_ASP_mis_equipmentdatamanage_aspx() {
            return new ASP.mis_equipmentdatamanage_aspx();
        }
        
        static object Create_ASP_mis_project_amdq_aspx() {
            return new ASP.mis_project_amdq_aspx();
        }
        
        static object Create_ASP_mis_equipment_show_aspx() {
            return new ASP.mis_equipment_show_aspx();
        }
        
        static object Create_ASP_mis_companylist_aspx() {
            return new ASP.mis_companylist_aspx();
        }
        
        static object Create_ASP_mis_devicecheck_q_aspx() {
            return new ASP.mis_devicecheck_q_aspx();
        }
        
        static object Create_ASP_mis_contractmanage_aspx() {
            return new ASP.mis_contractmanage_aspx();
        }
    }
}
