#pragma checksum "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "06D5085E91AEF5858CE3F6FFB15E9D64A5C01AED"
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Statistics_StudyFileUpload_A : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 30 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
    
    #line default
    #line hidden
    
    
    #line 31 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    protected global::AjaxControlToolkit.AjaxFileUpload AjaxFileUpload1;
    
    #line default
    #line hidden
    
    
    #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    protected global::System.Web.UI.WebControls.Button cmd_Back;
    
    #line default
    #line hidden
    
    
    #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 30 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    using AjaxControlToolkit;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
    using System.Web.UI.DataVisualization.Charting;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class statistics_studyfileupload_a_aspx : global::Statistics_StudyFileUpload_A, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public statistics_studyfileupload_a_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Statistics/StudyFileUpload_A.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.statistics_studyfileupload_a_aspx.@__initialized == false)) {
                global::ASP.statistics_studyfileupload_a_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[3];
                dependencies[0] = "~/Statistics/StudyFileUpload_A.aspx";
                dependencies[1] = "~/Statistics/StudyFileUpload_A.aspx.cs";
                dependencies[2] = "~/checkpass.inc";
                global::ASP.statistics_studyfileupload_a_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.statistics_studyfileupload_a_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.Href = "../css/bootstrap/bootstrap-responsive.css";
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.Href = "../css/bootstrap/bootstrap.css";
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.Href = "../css/manage.css";
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.Href = "../css/impromptu.css";
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "Stylesheet");
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control7() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 15 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 15 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("統計與查詢-檢修技術查詢"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 17 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 17 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("http-equiv", "Content-Type");
            
            #line default
            #line hidden
            
            #line 17 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.Content = "text/html; charset=utf-8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl1;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl2;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl3;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl4;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl4 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    <script type=\"text/javascript\" src=\"../javascript/jquery-1.3.2.js\"></scri" +
                        "pt>\r\n\r\n    <script type=\"text/javascript\" src=\"../javascript/jquery-impromptu.2." +
                        "8.min.js\"></script>\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl5;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl5 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl6;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl6 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.ToolkitScriptManager @__BuildControlToolkitScriptManager1() {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl;
            
            #line 30 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::AjaxControlToolkit.ToolkitScriptManager();
            
            #line default
            #line hidden
            this.ToolkitScriptManager1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 30 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.ID = "ToolkitScriptManager1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.AjaxFileUpload @__BuildControlAjaxFileUpload1() {
            global::AjaxControlToolkit.AjaxFileUpload @__ctrl;
            
            #line 31 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::AjaxControlToolkit.AjaxFileUpload();
            
            #line default
            #line hidden
            this.AjaxFileUpload1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 31 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.ID = "AjaxFileUpload1";
            
            #line default
            #line hidden
            
            #line 31 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.AllowedFileTypes = "jpg,jpeg,png,gif,pdf,doc,docx";
            
            #line default
            #line hidden
            
            #line 31 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.MaximumNumberOfFiles = 10;
            
            #line default
            #line hidden
            
            #line 31 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(500D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 31 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.UploadComplete += new System.EventHandler<AjaxControlToolkit.AjaxFileUploadEventArgs>(this.File_Upload);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlcmd_Back() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.cmd_Back = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.ID = "cmd_Back";
            
            #line default
            #line hidden
            
            #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.Text = "回到上一頁";
            
            #line default
            #line hidden
            
            #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.CssClass = "btn btn-large btn-primary";
            
            #line default
            #line hidden
            
            #line 35 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.Click += new System.EventHandler(this.cmd_Back_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-signin form-horizontal-50");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <div class=\"container\">\r\n        <h3>檢修技術資料上傳</h3>\r\n        \r\n        <" +
                        "!--資料分隔請複製我，更改內文即可-->\r\n        <div class=\"devide-line\">\r\n            <hr />\r\n  " +
                        "      </div>\r\n        <!--end-->        \r\n         <div class=\"control-group\">\r\n" +
                        "         "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl1;
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl1 = this.@__BuildControlToolkitScriptManager1();
            
            #line default
            #line hidden
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n         "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.AjaxFileUpload @__ctrl2;
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl2 = this.@__BuildControlAjaxFileUpload1();
            
            #line default
            #line hidden
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl3;
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl3 = this.@__BuildControlcmd_Back();
            
            #line default
            #line hidden
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 20 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n      </div>\r\n       \r\n    \r\n    </div>\r\n    "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(statistics_studyfileupload_a_aspx @__ctrl) {
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\checkpass.inc"
  
 if(Session["LOGIN"]=="OK")
    {
        //登入成功，取得session
            
    }
    else
    {
        //沒有登入或是沒取得session
		Response.Write("<script>");
		Response.Write("window.alert('操作逾時，請重新登入');");
		Response.Write("window.open('../Index.aspx','_top')");
		Response.Write("</script>"); 
       // Response.Redirect("../Login.aspx");
    }

            
            #line default
            #line hidden
            @__w.Write("\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n<body>\r\n    ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n</body>\r\n</html>\r\n");
        }
        
        
        #line 912304 "D:\Source\DotNet\ParkingRepairSystemKAO\Statistics\StudyFileUpload_A.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.statistics_studyfileupload_a_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.statistics_studyfileupload_a_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -290563245;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
