//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.18408")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.0")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_yxas322n {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_yxas322n() {
        }
        
        static object Create_ASP_report_warrantynotifylist_aspx() {
            return new ASP.report_warrantynotifylist_aspx();
        }
        
        static object Create_ASP_report_warrantynotifyadd_aspx() {
            return new ASP.report_warrantynotifyadd_aspx();
        }
        
        static object Create_ASP_report_reportreturnlist_aspx() {
            return new ASP.report_reportreturnlist_aspx();
        }
        
        static object Create_ASP_report_repairmaintainlist_aspx() {
            return new ASP.report_repairmaintainlist_aspx();
        }
        
        static object Create_ASP_report_notificationconfirmwork_aspx() {
            return new ASP.report_notificationconfirmwork_aspx();
        }
        
        static object Create_ASP_report_reportreturnmanage_aspx() {
            return new ASP.report_reportreturnmanage_aspx();
        }
        
        static object Create_ASP_report_reportreviewlist_aspx() {
            return new ASP.report_reportreviewlist_aspx();
        }
    }
}
