//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.18408")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.0")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_kugghpdz {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_kugghpdz() {
        }
        
        static object Create_ASP_systemmaster_aspx() {
            return new ASP.systemmaster_aspx();
        }
        
        static object Create_ASP_main_aspx() {
            return new ASP.main_aspx();
        }
        
        static object Create_ASP_xpmenuuc_ascx() {
            return new ASP.xpmenuuc_ascx();
        }
        
        static object Create_ASP_authority_aspx() {
            return new ASP.authority_aspx();
        }
        
        static object Create_ASP_testchart_aspx() {
            return new ASP.testchart_aspx();
        }
        
        static object Create_ASP_banner_ceci_aspx() {
            return new ASP.banner_ceci_aspx();
        }
        
        static object Create_ASP_banner_aspx() {
            return new ASP.banner_aspx();
        }
        
        static object Create_ASP_inventorymaster_aspx() {
            return new ASP.inventorymaster_aspx();
        }
    }
}
