#pragma checksum "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9023C9481D27A1CC2F0D9A0716CF66632162E08C"
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------



public partial class MIS_Project_AM : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
    
    #line default
    #line hidden
    
    
    #line 44 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::AjaxControlToolkit.ToolkitScriptManager ScriptManager1;
    
    #line default
    #line hidden
    
    
    #line 46 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.HiddenField hidden_Action;
    
    #line default
    #line hidden
    
    
    #line 47 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.HiddenField hidden_projectno;
    
    #line default
    #line hidden
    
    
    #line 54 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_projectId;
    
    #line default
    #line hidden
    
    
    #line 56 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::AjaxControlToolkit.FilteredTextBoxExtender txt_projectId_FilteredTextBoxExtender;
    
    #line default
    #line hidden
    
    
    #line 62 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_projectName;
    
    #line default
    #line hidden
    
    
    #line 68 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_client;
    
    #line default
    #line hidden
    
    
    #line 74 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_startDate;
    
    #line default
    #line hidden
    
    
    #line 76 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::AjaxControlToolkit.MaskedEditExtender MaskedEditExtender1;
    
    #line default
    #line hidden
    
    
    #line 78 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::AjaxControlToolkit.MaskedEditValidator MaskedEditValidator2;
    
    #line default
    #line hidden
    
    
    #line 90 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_endDate;
    
    #line default
    #line hidden
    
    
    #line 92 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::AjaxControlToolkit.MaskedEditExtender MaskedEditExtender2;
    
    #line default
    #line hidden
    
    
    #line 94 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::AjaxControlToolkit.MaskedEditValidator MaskedEditValidator1;
    
    #line default
    #line hidden
    
    
    #line 106 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_warStartDate;
    
    #line default
    #line hidden
    
    
    #line 108 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::AjaxControlToolkit.MaskedEditExtender MaskedEditExtender3;
    
    #line default
    #line hidden
    
    
    #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::AjaxControlToolkit.MaskedEditValidator MaskedEditValidator3;
    
    #line default
    #line hidden
    
    
    #line 122 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.TextBox txt_warEndDate;
    
    #line default
    #line hidden
    
    
    #line 124 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::AjaxControlToolkit.MaskedEditExtender MaskedEditExtender4;
    
    #line default
    #line hidden
    
    
    #line 126 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::AjaxControlToolkit.MaskedEditValidator MaskedEditValidator4;
    
    #line default
    #line hidden
    
    
    #line 137 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.Button cmd_Save;
    
    #line default
    #line hidden
    
    
    #line 139 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.WebControls.Button cmd_Back;
    
    #line default
    #line hidden
    
    
    #line 143 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.UpdatePanel UpdatePanel1;
    
    #line default
    #line hidden
    
    
    #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 46 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 46 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 56 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    using AjaxControlToolkit;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 46 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 46 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 46 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 46 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
    using System.Web.UI.DataVisualization.Charting;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class mis_project_am_aspx : global::MIS_Project_AM, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public mis_project_am_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/MIS/Project_AM.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.mis_project_am_aspx.@__initialized == false)) {
                global::ASP.mis_project_am_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[3];
                dependencies[0] = "~/MIS/Project_AM.aspx";
                dependencies[1] = "~/MIS/Project_AM.aspx.cs";
                dependencies[2] = "~/checkpass.inc";
                global::ASP.mis_project_am_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.mis_project_am_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Href = "../css/bootstrap/bootstrap-responsive.css";
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 7 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Href = "../css/bootstrap/bootstrap.css";
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 8 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Href = "../css/manage.css";
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 9 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Href = "../css/impromptu.css";
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "Stylesheet");
            
            #line default
            #line hidden
            
            #line 10 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 13 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 13 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("保固設備管理-廠商資料維護"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControlHead1() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            this.Head1 = @__ctrl;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "Head1";
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl1;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl2;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl3;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl3 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl4;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl4 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <script type=\"text/javascript\" src=\"../javascript/jquery-1.3.2.js\"></script" +
                        ">\r\n    <script type=\"text/javascript\" src=\"../javascript/jquery-impromptu.2.8.mi" +
                        "n.js\"></script>\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl5;
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl5 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 6 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(1390, 918, false));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.ToolkitScriptManager @__BuildControlScriptManager1() {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl;
            
            #line 44 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::AjaxControlToolkit.ToolkitScriptManager();
            
            #line default
            #line hidden
            this.ScriptManager1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 44 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "ScriptManager1";
            
            #line default
            #line hidden
            
            #line 44 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.CombineScripts = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhidden_Action() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            
            #line 46 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            
            #line default
            #line hidden
            this.hidden_Action = @__ctrl;
            
            #line 46 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "hidden_Action";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhidden_projectno() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            
            #line 47 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            
            #line default
            #line hidden
            this.hidden_projectno = @__ctrl;
            
            #line 47 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "hidden_projectno";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_projectId() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 54 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_projectId = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 54 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "txt_projectId";
            
            #line default
            #line hidden
            
            #line 54 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.AutoCompleteType = global::System.Web.UI.WebControls.AutoCompleteType.Disabled;
            
            #line default
            #line hidden
            
            #line 54 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.CssClass = "span3";
            
            #line default
            #line hidden
            
            #line 54 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "請輸入");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.FilteredTextBoxExtender @__BuildControltxt_projectId_FilteredTextBoxExtender() {
            global::AjaxControlToolkit.FilteredTextBoxExtender @__ctrl;
            
            #line 56 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::AjaxControlToolkit.FilteredTextBoxExtender();
            
            #line default
            #line hidden
            this.txt_projectId_FilteredTextBoxExtender = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 56 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "txt_projectId_FilteredTextBoxExtender";
            
            #line default
            #line hidden
            
            #line 56 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.FilterType = global::AjaxControlToolkit.FilterTypes.Numbers;
            
            #line default
            #line hidden
            
            #line 56 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.TargetControlID = "txt_projectId";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_projectName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 62 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_projectName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 62 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "txt_projectName";
            
            #line default
            #line hidden
            
            #line 62 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.AutoCompleteType = global::System.Web.UI.WebControls.AutoCompleteType.Disabled;
            
            #line default
            #line hidden
            
            #line 62 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.CssClass = "span3";
            
            #line default
            #line hidden
            
            #line 62 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "請輸入");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_client() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 68 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_client = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 68 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "txt_client";
            
            #line default
            #line hidden
            
            #line 68 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.AutoCompleteType = global::System.Web.UI.WebControls.AutoCompleteType.Disabled;
            
            #line default
            #line hidden
            
            #line 68 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.CssClass = "span3";
            
            #line default
            #line hidden
            
            #line 68 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "請輸入");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_startDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 74 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_startDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 74 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "txt_startDate";
            
            #line default
            #line hidden
            
            #line 74 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.AutoCompleteType = global::System.Web.UI.WebControls.AutoCompleteType.Disabled;
            
            #line default
            #line hidden
            
            #line 74 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.CssClass = "span3";
            
            #line default
            #line hidden
            
            #line 74 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "請輸入");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.MaskedEditExtender @__BuildControlMaskedEditExtender1() {
            global::AjaxControlToolkit.MaskedEditExtender @__ctrl;
            
            #line 76 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::AjaxControlToolkit.MaskedEditExtender();
            
            #line default
            #line hidden
            this.MaskedEditExtender1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 76 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "MaskedEditExtender1";
            
            #line default
            #line hidden
            
            #line 76 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Enabled = true;
            
            #line default
            #line hidden
            
            #line 76 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.TargetControlID = "txt_startDate";
            
            #line default
            #line hidden
            
            #line 76 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.UserDateFormat = global::AjaxControlToolkit.MaskedEditUserDateFormat.YearMonthDay;
            
            #line default
            #line hidden
            
            #line 76 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.UserTimeFormat = global::AjaxControlToolkit.MaskedEditUserTimeFormat.TwentyFourHour;
            
            #line default
            #line hidden
            
            #line 76 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.MaskType = global::AjaxControlToolkit.MaskedEditType.DateTime;
            
            #line default
            #line hidden
            
            #line 76 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Mask = "9999/99/99 99:99:99";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.MaskedEditValidator @__BuildControlMaskedEditValidator2() {
            global::AjaxControlToolkit.MaskedEditValidator @__ctrl;
            
            #line 78 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::AjaxControlToolkit.MaskedEditValidator();
            
            #line default
            #line hidden
            this.MaskedEditValidator2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 78 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "MaskedEditValidator2";
            
            #line default
            #line hidden
            
            #line 78 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ControlToValidate = "txt_startDate";
            
            #line default
            #line hidden
            
            #line 78 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ControlExtender = "MaskedEditExtender1";
            
            #line default
            #line hidden
            
            #line 78 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.IsValidEmpty = false;
            
            #line default
            #line hidden
            
            #line 78 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.EmptyValueMessage = "不可為空";
            
            #line default
            #line hidden
            
            #line 78 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.InvalidValueMessage = "格式不正確";
            
            #line default
            #line hidden
            
            #line 78 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Static;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_endDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 90 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_endDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 90 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "txt_endDate";
            
            #line default
            #line hidden
            
            #line 90 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.AutoCompleteType = global::System.Web.UI.WebControls.AutoCompleteType.Disabled;
            
            #line default
            #line hidden
            
            #line 90 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.CssClass = "span3";
            
            #line default
            #line hidden
            
            #line 90 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "請輸入");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.MaskedEditExtender @__BuildControlMaskedEditExtender2() {
            global::AjaxControlToolkit.MaskedEditExtender @__ctrl;
            
            #line 92 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::AjaxControlToolkit.MaskedEditExtender();
            
            #line default
            #line hidden
            this.MaskedEditExtender2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 92 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "MaskedEditExtender2";
            
            #line default
            #line hidden
            
            #line 92 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Enabled = true;
            
            #line default
            #line hidden
            
            #line 92 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.TargetControlID = "txt_endDate";
            
            #line default
            #line hidden
            
            #line 92 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.UserDateFormat = global::AjaxControlToolkit.MaskedEditUserDateFormat.YearMonthDay;
            
            #line default
            #line hidden
            
            #line 92 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.UserTimeFormat = global::AjaxControlToolkit.MaskedEditUserTimeFormat.TwentyFourHour;
            
            #line default
            #line hidden
            
            #line 92 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.MaskType = global::AjaxControlToolkit.MaskedEditType.DateTime;
            
            #line default
            #line hidden
            
            #line 92 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Mask = "9999/99/99 99:99:99";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.MaskedEditValidator @__BuildControlMaskedEditValidator1() {
            global::AjaxControlToolkit.MaskedEditValidator @__ctrl;
            
            #line 94 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::AjaxControlToolkit.MaskedEditValidator();
            
            #line default
            #line hidden
            this.MaskedEditValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 94 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "MaskedEditValidator1";
            
            #line default
            #line hidden
            
            #line 94 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ControlToValidate = "txt_endDate";
            
            #line default
            #line hidden
            
            #line 94 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ControlExtender = "MaskedEditExtender2";
            
            #line default
            #line hidden
            
            #line 94 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.IsValidEmpty = false;
            
            #line default
            #line hidden
            
            #line 94 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.EmptyValueMessage = "不可為空";
            
            #line default
            #line hidden
            
            #line 94 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.InvalidValueMessage = "格式不正確";
            
            #line default
            #line hidden
            
            #line 94 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Static;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_warStartDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 106 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_warStartDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 106 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "txt_warStartDate";
            
            #line default
            #line hidden
            
            #line 106 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.AutoCompleteType = global::System.Web.UI.WebControls.AutoCompleteType.Disabled;
            
            #line default
            #line hidden
            
            #line 106 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.CssClass = "span3";
            
            #line default
            #line hidden
            
            #line 106 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "請輸入");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.MaskedEditExtender @__BuildControlMaskedEditExtender3() {
            global::AjaxControlToolkit.MaskedEditExtender @__ctrl;
            
            #line 108 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::AjaxControlToolkit.MaskedEditExtender();
            
            #line default
            #line hidden
            this.MaskedEditExtender3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 108 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "MaskedEditExtender3";
            
            #line default
            #line hidden
            
            #line 108 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Enabled = true;
            
            #line default
            #line hidden
            
            #line 108 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.TargetControlID = "txt_warStartDate";
            
            #line default
            #line hidden
            
            #line 108 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.UserDateFormat = global::AjaxControlToolkit.MaskedEditUserDateFormat.YearMonthDay;
            
            #line default
            #line hidden
            
            #line 108 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.UserTimeFormat = global::AjaxControlToolkit.MaskedEditUserTimeFormat.TwentyFourHour;
            
            #line default
            #line hidden
            
            #line 108 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.MaskType = global::AjaxControlToolkit.MaskedEditType.DateTime;
            
            #line default
            #line hidden
            
            #line 108 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Mask = "9999/99/99 99:99:99";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.MaskedEditValidator @__BuildControlMaskedEditValidator3() {
            global::AjaxControlToolkit.MaskedEditValidator @__ctrl;
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::AjaxControlToolkit.MaskedEditValidator();
            
            #line default
            #line hidden
            this.MaskedEditValidator3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "MaskedEditValidator3";
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ControlToValidate = "txt_warStartDate";
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ControlExtender = "MaskedEditExtender3";
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.IsValidEmpty = false;
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.EmptyValueMessage = "不可為空";
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.InvalidValueMessage = "格式不正確";
            
            #line default
            #line hidden
            
            #line 110 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Static;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_warEndDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 122 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txt_warEndDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 122 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "txt_warEndDate";
            
            #line default
            #line hidden
            
            #line 122 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.AutoCompleteType = global::System.Web.UI.WebControls.AutoCompleteType.Disabled;
            
            #line default
            #line hidden
            
            #line 122 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.CssClass = "span3";
            
            #line default
            #line hidden
            
            #line 122 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "請輸入");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.MaskedEditExtender @__BuildControlMaskedEditExtender4() {
            global::AjaxControlToolkit.MaskedEditExtender @__ctrl;
            
            #line 124 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::AjaxControlToolkit.MaskedEditExtender();
            
            #line default
            #line hidden
            this.MaskedEditExtender4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 124 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "MaskedEditExtender4";
            
            #line default
            #line hidden
            
            #line 124 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Enabled = true;
            
            #line default
            #line hidden
            
            #line 124 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.TargetControlID = "txt_warEndDate";
            
            #line default
            #line hidden
            
            #line 124 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.UserDateFormat = global::AjaxControlToolkit.MaskedEditUserDateFormat.YearMonthDay;
            
            #line default
            #line hidden
            
            #line 124 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.UserTimeFormat = global::AjaxControlToolkit.MaskedEditUserTimeFormat.TwentyFourHour;
            
            #line default
            #line hidden
            
            #line 124 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.MaskType = global::AjaxControlToolkit.MaskedEditType.DateTime;
            
            #line default
            #line hidden
            
            #line 124 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Mask = "9999/99/99 99:99:99";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.MaskedEditValidator @__BuildControlMaskedEditValidator4() {
            global::AjaxControlToolkit.MaskedEditValidator @__ctrl;
            
            #line 126 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::AjaxControlToolkit.MaskedEditValidator();
            
            #line default
            #line hidden
            this.MaskedEditValidator4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 126 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "MaskedEditValidator4";
            
            #line default
            #line hidden
            
            #line 126 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ControlToValidate = "txt_warEndDate";
            
            #line default
            #line hidden
            
            #line 126 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ControlExtender = "MaskedEditExtender4";
            
            #line default
            #line hidden
            
            #line 126 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.IsValidEmpty = false;
            
            #line default
            #line hidden
            
            #line 126 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.EmptyValueMessage = "不可為空";
            
            #line default
            #line hidden
            
            #line 126 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.InvalidValueMessage = "格式不正確";
            
            #line default
            #line hidden
            
            #line 126 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Static;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlcmd_Save() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 137 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.cmd_Save = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 137 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "cmd_Save";
            
            #line default
            #line hidden
            
            #line 137 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Text = "確認";
            
            #line default
            #line hidden
            
            #line 137 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.CssClass = "btn btn-large btn-primary ";
            
            #line default
            #line hidden
            
            #line 137 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Click += new System.EventHandler(this.cmd_Save_Click1);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlcmd_Back() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 139 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.cmd_Back = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 139 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "cmd_Back";
            
            #line default
            #line hidden
            
            #line 139 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Text = "取消";
            
            #line default
            #line hidden
            
            #line 139 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.CssClass = "btn btn-large btn-primary";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.AsyncPostBackTrigger @__BuildControl__control8() {
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl;
            
            #line 145 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.AsyncPostBackTrigger();
            
            #line default
            #line hidden
            
            #line 145 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ControlID = "cmd_Back";
            
            #line default
            #line hidden
            
            #line 145 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.EventName = "Click";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.AsyncPostBackTrigger @__BuildControl__control9() {
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl;
            
            #line 146 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.AsyncPostBackTrigger();
            
            #line default
            #line hidden
            
            #line 146 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ControlID = "cmd_Save";
            
            #line default
            #line hidden
            
            #line 146 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.EventName = "Click";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control7(System.Web.UI.UpdatePanelTriggerCollection @__ctrl) {
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl1;
            
            #line 143 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl1 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 143 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.AsyncPostBackTrigger @__ctrl2;
            
            #line 143 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl2 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 143 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel1() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            
            #line 143 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            
            #line default
            #line hidden
            this.UpdatePanel1 = @__ctrl;
            
            #line 143 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "UpdatePanel1";
            
            #line default
            #line hidden
            
            #line 143 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.UpdateMode = global::System.Web.UI.UpdatePanelUpdateMode.Conditional;
            
            #line default
            #line hidden
            
            #line 143 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            this.@__BuildControl__control7(@__ctrl.Triggers);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-signin form-horizontal-50");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <div>\r\n            "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl1;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl1 = this.@__BuildControlScriptManager1();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HiddenField @__ctrl2;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl2 = this.@__BuildControlhidden_Action();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HiddenField @__ctrl3;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl3 = this.@__BuildControlhidden_projectno();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <div class=\"container\">\r\n            <h3>計畫資料維護</h3>\r\n            <div " +
                        "class=\"control-group \">\r\n                <label class=\"control-label\">\r\n        " +
                        "            計畫編號</label>\r\n                <div class=\"controls\">\r\n              " +
                        "      "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl4 = this.@__BuildControltxt_projectId();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.FilteredTextBoxExtender @__ctrl5;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl5 = this.@__BuildControltxt_projectId_FilteredTextBoxExtender();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n                <label class=\"control-label\">\r\n        " +
                        "            計畫名稱</label>\r\n                <div class=\"controls\">\r\n              " +
                        "      "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl6 = this.@__BuildControltxt_projectName();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n                <label class=\"control-label\">\r\n        " +
                        "            業主名稱</label>\r\n                <div class=\"controls\">\r\n              " +
                        "      "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl7 = this.@__BuildControltxt_client();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n                <label class=\"control-label\">\r\n        " +
                        "            起始日期</label>\r\n                <div class=\"controls\">\r\n              " +
                        "      "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl8 = this.@__BuildControltxt_startDate();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                     "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.MaskedEditExtender @__ctrl9;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl9 = this.@__BuildControlMaskedEditExtender1();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.MaskedEditValidator @__ctrl10;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl10 = this.@__BuildControlMaskedEditValidator2();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n                <label class=\"control-label\">\r\n        " +
                        "            結束日期</label>\r\n                <div class=\"controls\">\r\n              " +
                        "      "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl11;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl11 = this.@__BuildControltxt_endDate();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                     "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.MaskedEditExtender @__ctrl12;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl12 = this.@__BuildControlMaskedEditExtender2();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.MaskedEditValidator @__ctrl13;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl13 = this.@__BuildControlMaskedEditValidator1();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n                <label class=\"control-label\">\r\n        " +
                        "            保固起始日期</label>\r\n                <div class=\"controls\">\r\n            " +
                        "        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl14 = this.@__BuildControltxt_warStartDate();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                     "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.MaskedEditExtender @__ctrl15;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl15 = this.@__BuildControlMaskedEditExtender3();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.MaskedEditValidator @__ctrl16;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl16 = this.@__BuildControlMaskedEditValidator3();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n                <label class=\"control-label\">\r\n        " +
                        "            保固結束日期</label>\r\n                <div class=\"controls\">\r\n            " +
                        "        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl17;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl17 = this.@__BuildControltxt_warEndDate();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                     "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.MaskedEditExtender @__ctrl18;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl18 = this.@__BuildControlMaskedEditExtender4();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.MaskedEditValidator @__ctrl19;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl19 = this.@__BuildControlMaskedEditValidator4();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n               \r\n                <div class=\"controls\" " +
                        ">\r\n                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl20;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl20 = this.@__BuildControlcmd_Save();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl20);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl21;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl21 = this.@__BuildControlcmd_Back();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl21);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n            </div>\r\n        </div>\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.UpdatePanel @__ctrl22;
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl22 = this.@__BuildControlUpdatePanel1();
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl22);
            
            #line default
            #line hidden
            
            #line 42 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(mis_project_am_aspx @__ctrl) {
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl1 = this.@__BuildControlHead1();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            
            #line 1 "D:\Source\DotNet\ParkingRepairSystemKAO\checkpass.inc"
  
 if(Session["LOGIN"]=="OK")
    {
        //登入成功，取得session
            
    }
    else
    {
        //沒有登入或是沒取得session
		Response.Write("<script>");
		Response.Write("window.alert('操作逾時，請重新登入');");
		Response.Write("window.open('../Index.aspx','_top')");
		Response.Write("</script>"); 
       // Response.Redirect("../Login.aspx");
    }

            
            #line default
            #line hidden
            @__w.Write("\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.o" +
                    "rg/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/" +
                    "xhtml\">\r\n");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n<body>\r\n    ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n</body>\r\n</html>\r\n");
        }
        
        
        #line 912304 "D:\Source\DotNet\ParkingRepairSystemKAO\MIS\Project_AM.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.mis_project_am_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.mis_project_am_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1315328840;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
