'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.18408
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Microsoft.VisualBasic
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.ComponentModel.DataAnnotations
Imports System.Configuration
Imports System.Linq
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Web
Imports System.Web.Caching
Imports System.Web.DynamicData
Imports System.Web.Profile
Imports System.Web.Security
Imports System.Web.SessionState
Imports System.Web.UI
Imports System.Web.UI.HtmlControls
Imports System.Web.UI.WebControls
Imports System.Web.UI.WebControls.WebParts
Imports System.Xml.Linq

Namespace ASP
    
    <System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()>  _
    Public Class MyGVSkin
        Inherits Global.System.Web.UI.PageTheme
        
        Private __controlSkins As System.Collections.Specialized.HybridDictionary = New System.Collections.Specialized.HybridDictionary(0)
        
        Private __linkedStyleSheets() As String = Nothing
        
        Private Shared __initialized As Boolean
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            If (Global.ASP.MyGVSkin.__initialized = false) Then
                Global.ASP.MyGVSkin.__initialized = true
            End If
        End Sub
        
        Protected Overrides ReadOnly Property AppRelativeTemplateSourceDirectory() As String
            Get
                Return "/D:/Source/DotNet/ParkingRepairSystemKAO/App_Themes/MyGVSkin/"
            End Get
        End Property
        
        Protected Overrides ReadOnly Property ControlSkins() As System.Collections.IDictionary
            Get
                Return Me.__controlSkins
            End Get
        End Property
        
        Protected Overrides ReadOnly Property LinkedStyleSheets() As String()
            Get
                Return Me.__linkedStyleSheets
            End Get
        End Property
    End Class
End Namespace
